schema_version: '1.0'
protocol: SR-01
session_id: e68b3f48
timestamp: '2026-01-12T13:20:25Z'
triggered_by: script
pipeline:
  scripts:
    status: skipped
    output: No build script
  container:
    status: completed
    images_built:
    - backend
    - worker
  deploy:
    status: completed
    services_started:
    - backend
    - worker
  tests:
    status: passed
    passed: 4525
    failed: 0
    skipped: 136
  git_commit:
    status: failed
    error: "Running quick CI consistency check...\n\n\e[0;36m+====================================================================+\e\
      [0m\n\e[0;36m|  AGENTICVERZ/MN-OS Milestone Certification Engine v5.1      \
      \      |\e[0"
verdict: RECONCILIATION_BLOCKED
exit_ready: false
blocking_reason: Pipeline step failed
