# AOS Models Package
"""
SQLAlchemy models for async database access.

This package contains pure SQLAlchemy models (not SQLModel) for use with
async sessions. These models mirror the SQLModel definitions in db.py
but are designed for async operations.
"""

from app.models.contract import (
    TERMINAL_STATES,
    VALID_TRANSITIONS,
    AuditVerdict,
    ContractApproval,
    ContractCreate,
    ContractImmutableError,
    ContractRejection,
    ContractResponse,
    ContractSource,
    ContractStatus,
    InvalidTransitionError,
    MayNotVerdictError,
    ProposedChangeType,
    RiskLevel,
    SystemContract,
)
from app.models.costsim_cb import (
    Base,
    CostSimAlertQueueModel,
    CostSimCBIncidentModel,
    CostSimCBStateModel,
    CostSimProvenanceModel,
)
from app.models.external_response import (
    ExternalResponse,
    ExternalResponseCreate,
    ExternalResponseRead,
    InterpretationUpdate,
    InterpretedResponse,
)
from app.models.governance import (
    GovernanceCheckResult,
    GovernanceSignal,
    GovernanceSignalCreate,
    GovernanceSignalQuery,
    GovernanceSignalResponse,
)
from app.models.governance_job import (
    JOB_TERMINAL_STATES,
    JOB_VALID_TRANSITIONS,
    GovernanceJob,
    HealthSnapshot,
    InvalidJobTransitionError,
    JobCreate,
    JobImmutableError,
    JobResponse,
    JobStatus,
    JobStep,
    JobTransitionRecord,
    OrphanJobError,
    StepResult,
    StepStatus,
)
from app.models.tenant import (
    PLAN_QUOTAS,
    APIKey,
    AuditLog,
    Subscription,
    Tenant,
    TenantMembership,
    UsageRecord,
    User,
    WorkerConfig,
    WorkerRegistry,
    WorkerRun,
)
from app.models.policy_control_plane import (
    BreachType,
    EnforcementAction,
    EnforcementMode,
    Limit,
    LimitBreach,
    LimitCategory,
    LimitConsequence,
    LimitEnforcement,
    LimitOverride,
    LimitScope,
    LimitStatus,
    PolicyEnforcement,
    PolicyRule,
    PolicyRuleStatus,
    PolicyScope,
    PolicySource,
    ResetPeriod,
)
from app.models.audit_ledger import (
    ActorType,
    AuditEntityType,
    AuditEventType,
    AuditLedger,
)
from app.models.logs_records import (
    ExecutionStatus,
    LLMRunRecord,
    RecordSource,
    SystemCausedBy,
    SystemComponent,
    SystemEventType,
    SystemRecord,
    SystemSeverity,
)
# Run Lifecycle Models (BACKEND_REMEDIATION_PLAN GAP-002, GAP-007)
from app.models.run_lifecycle import (
    PolicyViolationType,
    RunLifecycleState,
    RunStatus,
    RunTerminationInfo,
    RunTerminationReason,
    RunViolationInfo,
    SEVERITY_PRIORITY,
    TERMINATION_TO_STATUS,
    ViolationSeverity,
    get_lifecycle_state,
)
# Policy Snapshot Model (BACKEND_REMEDIATION_PLAN GAP-006)
from app.models.policy_snapshot import (
    PolicySnapshot,
    PolicySnapshotCreate,
    PolicySnapshotResponse,
    ThresholdSnapshot,
)
# Export Bundle Models (BACKEND_REMEDIATION_PLAN GAP-008)
from app.models.export_bundles import (
    DEFAULT_SOC2_CONTROLS,
    EvidenceBundle,
    ExecutiveDebriefBundle,
    ExportBundleRequest,
    ExportBundleResponse,
    PolicyContext,
    SOC2Bundle,
    SOC2ControlMapping,
    TraceStepEvidence,
)
# MCP Models (PIN-516, GAP-170)
from app.models.mcp_models import (
    McpActorType,
    McpAuthType,
    McpInvocationOutcome,
    McpPolicyDecision,
    McpRiskLevel,
    McpServer,
    McpServerCreate,
    McpServerHealthStatus,
    McpServerResponse,
    McpServerStatus,
    McpServerUpdate,
    McpTool,
    McpToolDiscoveryResult,
    McpToolInvocation,
    McpToolInvocationCreate,
    McpToolInvocationResponse,
    McpToolResponse,
    McpToolUpdate,
    McpTransport,
)

__all__ = [
    "Base",
    "CostSimCBStateModel",
    "CostSimCBIncidentModel",
    "CostSimProvenanceModel",
    "CostSimAlertQueueModel",
    # Governance models (Phase E FIX-03)
    "GovernanceSignal",
    "GovernanceSignalCreate",
    "GovernanceSignalResponse",
    "GovernanceSignalQuery",
    "GovernanceCheckResult",
    # External response models (Phase E FIX-04)
    "ExternalResponse",
    "ExternalResponseCreate",
    "ExternalResponseRead",
    "InterpretationUpdate",
    "InterpretedResponse",
    # Tenant models (M21)
    "Tenant",
    "User",
    "TenantMembership",
    "APIKey",
    "Subscription",
    "UsageRecord",
    "WorkerRegistry",
    "WorkerConfig",
    "WorkerRun",
    "AuditLog",
    "PLAN_QUOTAS",
    # Contract models (Part-2 PIN-291)
    "SystemContract",
    "ContractStatus",
    "ContractSource",
    "AuditVerdict",
    "RiskLevel",
    "ProposedChangeType",
    "ContractCreate",
    "ContractResponse",
    "ContractApproval",
    "ContractRejection",
    "InvalidTransitionError",
    "ContractImmutableError",
    "MayNotVerdictError",
    "TERMINAL_STATES",
    "VALID_TRANSITIONS",
    # Governance Job models (Part-2 PIN-292)
    "GovernanceJob",
    "JobStatus",
    "StepStatus",
    "JobStep",
    "StepResult",
    "HealthSnapshot",
    "JobCreate",
    "JobResponse",
    "JobTransitionRecord",
    "JOB_TERMINAL_STATES",
    "JOB_VALID_TRANSITIONS",
    "InvalidJobTransitionError",
    "JobImmutableError",
    "OrphanJobError",
    # Policy Control-Plane models (PIN-412)
    "PolicyRule",
    "PolicyRuleStatus",
    "PolicyScope",
    "PolicySource",
    "EnforcementMode",
    "EnforcementAction",
    "PolicyEnforcement",
    "Limit",
    "LimitCategory",
    "LimitScope",
    "LimitEnforcement",
    "LimitConsequence",
    "LimitStatus",
    "ResetPeriod",
    "LimitBreach",
    "LimitOverride",
    "BreachType",
    # Audit Ledger model - Logs domain (PIN-413 CORRECTED)
    "AuditLedger",
    "ActorType",
    "AuditEntityType",
    "AuditEventType",
    # LLM Run Records and System Records - Logs domain (PIN-413 Expansion)
    "LLMRunRecord",
    "ExecutionStatus",
    "RecordSource",
    "SystemRecord",
    "SystemComponent",
    "SystemEventType",
    "SystemSeverity",
    "SystemCausedBy",
    # Run Lifecycle Models (BACKEND_REMEDIATION_PLAN GAP-002, GAP-007)
    "RunTerminationReason",
    "RunStatus",
    "RunLifecycleState",
    "PolicyViolationType",
    "ViolationSeverity",
    "RunViolationInfo",
    "RunTerminationInfo",
    "TERMINATION_TO_STATUS",
    "SEVERITY_PRIORITY",
    "get_lifecycle_state",
    # Policy Snapshot Model (BACKEND_REMEDIATION_PLAN GAP-006)
    "PolicySnapshot",
    "PolicySnapshotCreate",
    "PolicySnapshotResponse",
    "ThresholdSnapshot",
    # Export Bundle Models (BACKEND_REMEDIATION_PLAN GAP-008)
    "TraceStepEvidence",
    "PolicyContext",
    "EvidenceBundle",
    "SOC2ControlMapping",
    "SOC2Bundle",
    "ExecutiveDebriefBundle",
    "ExportBundleRequest",
    "ExportBundleResponse",
    "DEFAULT_SOC2_CONTROLS",
    # MCP Models (PIN-516, GAP-170)
    "McpServer",
    "McpTool",
    "McpToolInvocation",
    "McpServerStatus",
    "McpTransport",
    "McpAuthType",
    "McpRiskLevel",
    "McpPolicyDecision",
    "McpInvocationOutcome",
    "McpActorType",
    "McpServerCreate",
    "McpServerResponse",
    "McpServerUpdate",
    "McpToolResponse",
    "McpToolUpdate",
    "McpToolInvocationCreate",
    "McpToolInvocationResponse",
    "McpServerHealthStatus",
    "McpToolDiscoveryResult",
]
