openapi: 3.0.3
info:
  title: AOS Traces API
  description: |
    Trace storage, query, and replay verification API for AOS.

    Supports:
    - Deterministic trace storage with v1.1 schema
    - Trace search by root_hash, plan_hash, seed, tenant
    - Cross-language parity verification
    - Replay safety with idempotency controls
  version: "1.1.0"
  contact:
    name: AOS Team
    url: https://github.com/agenticverz/aos

servers:
  - url: http://localhost:8000
    description: Local development
  - url: https://api.aos.example.com
    description: Production

paths:
  /api/v1/simulate:
    post:
      summary: Simulate a plan and optionally store trace
      description: |
        Runs plan simulation with deterministic context.
        Returns trace_id and root_hash for verification.
      operationId: simulatePlan
      tags: [simulate]
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulateRequest'
            examples:
              basic:
                summary: Basic simulation
                value:
                  plan:
                    - skill: http_call
                      params:
                        url: "https://api.example.com/data"
                  seed: 42
                  save_trace: true
      responses:
        '200':
          description: Simulation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulateResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/RateLimited'

  /api/v1/traces:
    get:
      summary: Search and list traces
      description: |
        Search traces with multiple filter criteria.
        Supports pagination for large result sets.
      operationId: listTraces
      tags: [traces]
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: tenant_id
          in: query
          description: Filter by tenant ID (required for non-admin users)
          schema:
            type: string
        - name: agent_id
          in: query
          description: Filter by agent ID
          schema:
            type: string
        - name: root_hash
          in: query
          description: Filter by deterministic root hash
          schema:
            type: string
        - name: plan_hash
          in: query
          description: Filter by plan content hash
          schema:
            type: string
        - name: seed
          in: query
          description: Filter by random seed
          schema:
            type: integer
        - name: status
          in: query
          description: Filter by status
          schema:
            type: string
            enum: [running, completed, failed]
        - name: from_date
          in: query
          description: Filter from date (ISO8601)
          schema:
            type: string
            format: date-time
        - name: to_date
          in: query
          description: Filter to date (ISO8601)
          schema:
            type: string
            format: date-time
        - name: limit
          in: query
          description: Maximum results (1-1000)
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 1000
        - name: offset
          in: query
          description: Pagination offset
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: List of traces
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      summary: Store a client-provided trace
      description: |
        Store a trace generated by the SDK.
        Validates root_hash integrity before storage.
      operationId: storeTrace
      tags: [traces]
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreTraceRequest'
      responses:
        '201':
          description: Trace stored
          content:
            application/json:
              schema:
                type: object
                properties:
                  trace_id:
                    type: string
                  root_hash:
                    type: string
                  stored:
                    type: boolean
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Trace already exists (use overwrite=true to replace)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/traces/{trace_id}:
    get:
      summary: Get trace by ID
      description: |
        Retrieve a complete trace with all steps.
        PII fields are redacted based on policy.
      operationId: getTrace
      tags: [traces]
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: trace_id
          in: path
          required: true
          description: Trace ID or run_id
          schema:
            type: string
      responses:
        '200':
          description: Trace object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceDetail'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete trace by ID
      description: |
        Delete a trace. Requires admin or operator role.
      operationId: deleteTrace
      tags: [traces]
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: trace_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Trace deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/traces/by-hash/{root_hash}:
    get:
      summary: Get trace by root hash
      description: |
        Find a trace by its deterministic root hash.
        Useful for replay verification.
      operationId: getTraceByHash
      tags: [traces]
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: root_hash
          in: path
          required: true
          description: SHA256 root hash
          schema:
            type: string
            pattern: '^[a-f0-9]{64}$'
      responses:
        '200':
          description: Trace object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceDetail'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/traces/compare/{trace_id1}/{trace_id2}:
    get:
      summary: Compare two traces for deterministic equality
      description: |
        Compare root_hash and step hashes to verify replay parity.
      operationId: compareTraces
      tags: [traces]
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: trace_id1
          in: path
          required: true
          schema:
            type: string
        - name: trace_id2
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Comparison result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceCompareResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/traces/cleanup:
    post:
      summary: Delete old traces (retention policy)
      description: |
        Delete traces older than specified days.
        Requires admin role.
      operationId: cleanupTraces
      tags: [traces, admin]
      security:
        - bearerAuth: []
      parameters:
        - name: days
          in: query
          description: Delete traces older than N days
          schema:
            type: integer
            default: 30
            minimum: 1
            maximum: 365
      responses:
        '200':
          description: Cleanup result
          content:
            application/json:
              schema:
                type: object
                properties:
                  deleted_count:
                    type: integer
                  retention_days:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

components:
  schemas:
    SimulateRequest:
      type: object
      required: [plan]
      properties:
        plan:
          type: array
          items:
            type: object
          description: Execution plan steps
        seed:
          type: integer
          description: Random seed for determinism
          default: 42
        timestamp:
          type: string
          format: date-time
          description: Frozen timestamp (ISO8601)
        save_trace:
          type: boolean
          description: Store trace after simulation
          default: false
        budget_cents:
          type: integer
          description: Maximum budget for simulation
          default: 100

    SimulateResponse:
      type: object
      properties:
        trace_id:
          type: string
          description: Unique trace identifier
        root_hash:
          type: string
          description: Deterministic root hash (SHA256)
        seed:
          type: integer
        feasible:
          type: boolean
        estimated_cost_cents:
          type: number
        step_simulations:
          type: array
          items:
            type: object

    StoreTraceRequest:
      type: object
      required: [trace]
      properties:
        trace:
          type: object
          description: Complete trace object from SDK
        overwrite:
          type: boolean
          default: false
          description: Overwrite if trace_id exists

    TraceListResponse:
      type: object
      properties:
        traces:
          type: array
          items:
            $ref: '#/components/schemas/TraceSummary'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    TraceSummary:
      type: object
      properties:
        trace_id:
          type: string
        run_id:
          type: string
        tenant_id:
          type: string
        agent_id:
          type: string
          nullable: true
        root_hash:
          type: string
        seed:
          type: integer
        total_steps:
          type: integer
        status:
          type: string
          enum: [running, completed, failed]
        created_at:
          type: string
          format: date-time

    TraceDetail:
      type: object
      properties:
        trace_id:
          type: string
        run_id:
          type: string
        correlation_id:
          type: string
        tenant_id:
          type: string
        agent_id:
          type: string
          nullable: true
        plan:
          type: array
          items:
            type: object
        steps:
          type: array
          items:
            $ref: '#/components/schemas/TraceStep'
        seed:
          type: integer
        frozen_timestamp:
          type: string
          nullable: true
        root_hash:
          type: string
        plan_hash:
          type: string
          nullable: true
        schema_version:
          type: string
          default: "1.1"
        status:
          type: string
        metadata:
          type: object
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true

    TraceStep:
      type: object
      properties:
        step_index:
          type: integer
        skill_id:
          type: string
        skill_name:
          type: string
        params:
          type: object
        status:
          type: string
          enum: [pending, running, success, failure, skipped]
        outcome_category:
          type: string
        outcome_code:
          type: string
          nullable: true
        outcome_data:
          type: object
          nullable: true
        cost_cents:
          type: number
        duration_ms:
          type: number
        retry_count:
          type: integer
        input_hash:
          type: string
          nullable: true
        output_hash:
          type: string
          nullable: true
        rng_state_before:
          type: string
          nullable: true
        idempotency_key:
          type: string
          nullable: true
        replay_behavior:
          type: string
          enum: [execute, skip, check]
          default: execute
        timestamp:
          type: string
          format: date-time

    TraceCompareResponse:
      type: object
      properties:
        match:
          type: boolean
        trace1_root_hash:
          type: string
          nullable: true
        trace2_root_hash:
          type: string
          nullable: true
        differences:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              trace1:
                type: string
              trace2:
                type: string
        summary:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        detail:
          type: string
          nullable: true

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    RateLimited:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

tags:
  - name: simulate
    description: Plan simulation endpoints
  - name: traces
    description: Trace storage and query endpoints
  - name: admin
    description: Administrative endpoints
