#!/bin/bash
# Setup automatic CI consistency checks via git hooks
#
# This script installs:
# 1. pre-commit hook - Quick check before every commit
# 2. pre-push hook - Full check before pushing to remote
#
# Usage: ./scripts/ops/setup_ci_hooks.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "Setting up CI consistency check hooks..."

# Ensure .git/hooks exists
mkdir -p "$HOOKS_DIR"

# Create pre-commit hook
cat > "$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/bash
# Auto-generated by setup_ci_hooks.sh
# Quick CI consistency check before commit

SCRIPT="./scripts/ops/ci_consistency_check.sh"

if [[ -x "$SCRIPT" ]]; then
    echo "Running quick CI consistency check..."
    $SCRIPT --quick
    exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
        echo ""
        echo "CI consistency check failed. Fix issues or use 'git commit --no-verify' to skip."
        exit 1
    fi
else
    echo "Warning: CI consistency check script not found at $SCRIPT"
fi
EOF

chmod +x "$HOOKS_DIR/pre-commit"
echo -e "${GREEN}[OK]${NC} Installed pre-commit hook"

# Create pre-push hook
cat > "$HOOKS_DIR/pre-push" << 'EOF'
#!/bin/bash
# Auto-generated by setup_ci_hooks.sh
# Full CI consistency check before push

SCRIPT="./scripts/ops/ci_consistency_check.sh"

if [[ -x "$SCRIPT" ]]; then
    echo "Running full CI consistency check before push..."
    $SCRIPT
    exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
        echo ""
        echo "CI consistency check failed. Fix issues or use 'git push --no-verify' to skip."
        exit 1
    fi
else
    echo "Warning: CI consistency check script not found at $SCRIPT"
fi
EOF

chmod +x "$HOOKS_DIR/pre-push"
echo -e "${GREEN}[OK]${NC} Installed pre-push hook"

echo ""
echo -e "${GREEN}Git hooks installed successfully!${NC}"
echo ""
echo "Hooks will run automatically:"
echo "  - pre-commit: Quick check (--quick) on every commit"
echo "  - pre-push: Full check before pushing to remote"
echo ""
echo "To skip temporarily: git commit --no-verify / git push --no-verify"
echo "To uninstall: rm .git/hooks/pre-commit .git/hooks/pre-push"
